### ISSUE TITLE
Allow stepping into functions with the VSCode debugger

### ISSUE THREAD

**Issue by thomasballinger** [get-convex/convex-test#5]
Michal says if we didn't dynamically import functions maybe we could step into them.

(if I understand right)

We could codegen an api-like object that has all the functions attached, or we could change the api to require importing them statically to run them?

**Comment by xixixao** [comment]
Thread for context: https://discord.com/channels/1019350475847499849/1230211387230392422

This might be fixable in Vitest or VS Code as well.

**Comment by xixixao** [comment]
I noticed that `debugger;` statement works

**Comment by xixixao** [comment]
This was fixed.
